### ISSUE TITLE
storage: fix objects handles (user or server) see `User-specified IDs`

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-api#143]
In the current OPI storage API, the handles are int64 "id"s, and are "mostly" assigned by the gRPC client (except for NVMeSubsystemCreate). 

In the proposed PR #133 handles are keys defined to be 128bits opaque values?

To be most flexible, shouldn't the handles be opaque strings returned by the gRPC server ?

we also don't conform to [Google's AIP](https://google.aip.dev/133) (ex. Create functions should return the created object and not a CreateResponse).

**Comment by glimchb** [comment]
@llabordehpe FYI

**Comment by jainvipin** [comment]
I agree it should be opaque set of `bytes` (not perhaps `strings` that are null terminated). So #133 has it as bytes. Having said that bytes without a length will still require an understanding on the size of it. So 128bit i.e. 16bytes looked good, which can also cover standard UUID in them.

**Comment by llabordehpe** [comment]
If the API provider assigns the handle upon object creation, the API user doesn't need to know the length, right?

**Comment by jainvipin** [comment]
yes @llabordehpe - wouldn't client need to know how many bytes to parse/read, so either we make it null terminated string e.g. uuid that is null terminated, or specify the length somehow. So in that sense I am good with a string either.

**Comment by jainvipin** [comment]
having said that the @glimchb - the way it is defined in #133, it is an opaque string. 128bits is just specified the documentation.

**Comment by glimchb** [comment]
@PWAlessi FYI

**Comment by glimchb** [comment]
@jainvipin @llabordehpe do you agree ? @PWAlessi is implementing this as string...

**Comment by llabordehpe** [comment]
@PWAlessi: I thought there were issues when using "string" for opaque handles. Can you really have any binary content in a tring, like 0-value bytes ?

**Comment by seroyer** [comment]
@llabordehpe no it's not a good idea to directly put binary data into a string value.  However, the implementation that requires a binary value can encode or more generally serialize that value into a string however it likes.  Common choices might be hexadecimal or uuencode.  It's up to the implementation to then take that opaque string and decode/deserialize that value back into whatever it needs on the back end.

**Comment by glimchb** [comment]
all please review #150 for new object type we will use as handle returned by Create()
For now it is string, we can change later on as this conversation in this thread evolves...

**Comment by jainvipin** [comment]
`keyId` string is what we used in updated PRs. should we close this issue?

**Comment by glimchb** [comment]
all the work was completed
see example (there are more) how user generated vs server generates is implemented
https://github.com/opiproject/opi-evpn-bridge/blob/71379e557df1718d439a8677fedbdd7373c54a50/pkg/evpn/bridge.go#L43-L55
