### ISSUE TITLE
add `google.api.field_behavior` optional/mandatory

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-api#198]
see https://linter.aip.dev/203/optional and https://google.aip.dev/203
example:
```
diff --git a/storage/v1alpha1/frontend_nvme_pcie.proto b/storage/v1alpha1/frontend_nvme_pcie.proto
index 610239e..303b684 100755
--- a/storage/v1alpha1/frontend_nvme_pcie.proto
+++ b/storage/v1alpha1/frontend_nvme_pcie.proto
@@ -15,8 +15,10 @@ import "object_key.proto";
 import "uuid.proto";
 import "google/protobuf/empty.proto";
 import "google/api/annotations.proto";
+import "google/api/field_behavior.proto";

 // Front End (host-facing) APIs. Mostly used for NVMe/PCIe emulation and host presentation.
+
 service FrontendNvmeService {
     rpc NVMeSubsystemCreate (NVMeSubsystemCreateRequest) returns (NVMeSubsystem) {
         option (google.api.http) = {
@@ -151,7 +153,7 @@ message NVMeController {

     // maximum number of host completion queues allowed.
     // If not set, the xPU will provide a default.
-    int32 max_ncq = 6;
+    int32 max_ncq = 6 [(google.api.field_behavior) = OPTIONAL];

     // maximum number of submission queue entries per submission queue, as a power of 2.
     // default value as per spec is 6
@@ -195,7 +197,7 @@ message NVMeNamespace {

     // 64bit Extended unique identifier for the namespace
     // mandatory if guid is not specified
-    int64 eui64 = 8;
+    int64 eui64 = 8 [(google.api.field_behavior) = OPTIONAL];

     // Globally unique identifier for the namespace
     common.v1.Uuid uuid = 9;
(END)
```

**Comment by jainvipin** [comment]
I am curious about the intent of this issue:
- is suggesting that we use `google.api.field_behavior` to specify optional fields or use protobuf `optional` parameter, which specifies the protobuf encoding
- Is it suggesting that we we start labeling `optional`(and therefore mandator to the unlabeled fields) to currently defined APIs?

**Comment by glimchb** [comment]
Yes, Suggesting that we start labeling optional (and therefore mandator to the unlabeled fields) to currently defined APIs?

**Comment by artek-koltun** [comment]
`REQUIRED` annotation is definitely useful. In conjunction with [fieldbehavior.ValidateRequiredFields](https://pkg.go.dev/go.einride.tech/aip/fieldbehavior#ValidateRequiredFields) it can be a relative protection against nil pointer dereference in requests.

**Comment by glimchb** [comment]
frontend added by @artek-koltun #321

**Comment by glimchb** [comment]
done. all annotations are completed
- https://github.com/opiproject/opi-api/pull/344
- https://github.com/opiproject/opi-api/pull/330
- https://github.com/opiproject/opi-api/pull/325
- https://github.com/opiproject/opi-api/pull/324
- https://github.com/opiproject/opi-api/pull/321
- https://github.com/opiproject/opi-api/pull/317
