### ISSUE TITLE
think of a better name for `message Crypto`

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-api#210]
see #208 
@benlwalker 
```
Should we call it Crypto or CryptoVolume? Without the word "Volume" I think it leaves people room to misinterpret how this object really works. It's not the global crypto service, it's a specific volume (that may forward to another volume).
```
@jainvipin 
```
we could call it Encryption (vs. crypto which is more associated with  the currency, which may not confuse storage audience, but nevertheless). Crypto is also generic name for the domain not indicating encryption for transit traffic; will also comment on your PR 
```

**Comment by jainvipin** [comment]
I'd prefer it as `Encryption` and avoid marketing term in the proto definitions. Happy to submit a PR to address this.

**Comment by glimchb** [comment]
I'm fine with any naming, I don't have an opinion on this topic
can you chat with @benlwalker and agree ?

**Comment by glimchb** [comment]
@jainvipin , if `EncryptedVolume` is acceptable to you, please create PR

**Comment by jainvipin** [comment]
@benlwalker - it is specifying encryption parameters for a namespace (aka middleend volume object). So this is really a `Volume's encryption parameters` - so if we keep volume in this, `VolumeEncryption` is closer to what this does.

**Comment by glimchb** [comment]
@jainvipin you can create PR with `VolumeEncryption`

**Comment by jainvipin** [comment]
will do soon!

**Comment by benlwalker** [comment]
I think we're still not aligned on the OPI object model. You're thinking of the middle-end as services. OPI thinks of the middle-end as volume objects. In the OPI model, the right name is EncryptedVolume. -1 to VolumeEncryption.

**Comment by jainvipin** [comment]
yes that's the main difference - for someone who is sitting as a middle entity, this would sound like services. To be honest I am not too opinionated on this. So I will go with what @benlwalker is suggesting. will create a PR with `EncryptedVolume`
