### ISSUE TITLE
update slack channel link

### ISSUE THREAD

**Issue by xinydev** [opiproject/opi-api#266]
I am unable to join the slack channel through the current link(https://opi-project.slack.com/archives/C0344KMEAKB). It requires an @amd.com email address. 
Can we change the Slack channel link on the README to an invite link, like the one of SPDK(https://spdk.io/community/). So everyone else can join the channel, or is there an issue with my operation?

**Comment by seroyer** [comment]
@pdp2shirts what's the right answer here?

**Comment by pdp2shirts** [comment]
@xinydev the link on the API Readme.md for the channel within slack is a pointer to that slack for those who have already joined our slack workspace. The link to **join** our slack can be found on the [website](https://opiproject.org) in the upper right hand corner there is a slack icon with an invite link. For convenience, that link is [here](https://join.slack.com/t/opi-project/shared_invite/zt-1ctqtrgkz-WJZrcVPp3P1ACZWjpZP2KQ)

**Comment by pdp2shirts** [comment]
@seroyer It doesn't look like I have rights to close this issue, can you?

**Comment by seroyer** [comment]
Thanks Paul.  @xinydev please try the above and you can reopen if it still does not work.

**Comment by xinydev** [comment]
> @xinydev the link on the API Readme.md for the channel within slack is a pointer to that slack for those who have already joined our slack workspace. The link to **join** our slack can be found on the [website](https://opiproject.org) in the upper right hand corner there is a slack icon with an invite link. For convenience, that link is [here](https://join.slack.com/t/opi-project/shared_invite/zt-1ctqtrgkz-WJZrcVPp3P1ACZWjpZP2KQ)

@pdp2shirts Thank you so much. I'm sorry I didn't see the invite link on the website earlier. I have joined now.
