### ISSUE TITLE
proto file define the same http annotation with different rpc method

### ISSUE THREAD

**Issue by chujieyang** [opiproject/opi-api#303]
when i use grpc-gateway to proxy the storage gRPC service, i found the same http route in the .gw.pb files.

for example:  storage/v1alpha1/frontend_nvme_pcie.proto
```
rpc ListNvmeSubsystems   (ListNvmeSubsystemsRequest)   returns (ListNvmeSubsystemsResponse)   {
      option (google.api.http) = {
          get: "/v1/{parent=subsystems}"
      };
      option (google.api.method_signature) = "parent";
  }
```
and
```
rpc ListNvmeControllers   (ListNvmeControllersRequest)   returns (ListNvmeControllersResponse)   {
      option (google.api.http) = {
          get: "/v1/{parent=subsystems}"
      };
      option (google.api.method_signature) = "parent";
}
```
above two different rpc method: ListNvmeSubsystems、ListNvmeControllers  has the same http anotation url.

**Comment by artek-koltun** [comment]
Duplicates/relates to https://github.com/opiproject/opi-api/issues/188 ?

**Comment by chujieyang** [comment]
not the same, but the issue #188 can also resolve the problem after redfine the rpc methods http anotations according to business rules.

**Comment by glimchb** [comment]
@chujieyang can you propose a fix, please ?

**Comment by chujieyang** [comment]
I hava submit a pull request with the http anotations.  #331

**Comment by glimchb** [comment]
thanks!
