### ISSUE TITLE
Is `OUTPUT_ONLY` a correct annotation for `name` field ?

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-api#318]
Is `OUTPUT_ONLY` a correct annotation here?
This is a hard one... According to the annotation description:
```
including the field in a message in a request does nothing (the server must clear out any value in this field and must not throw an error as a result of the presence of a value in this field on input). Similarly, services must ignore the presence of output only fields in update field masks.
```
Based on that, a user cannot specify a `name`, since the server must ignore it. But this resource is used in Update call and `name` is used to find that resource internally...

This might be a resolution: 2 weeks ago [a PR](https://github.com/aip-dev/google.aip.dev/pull/1180) from an aip team member was created where it is said that `name` field must not be annotated.

_Originally posted by @artek-koltun in https://github.com/opiproject/opi-api/pull/317#discussion_r1281526799_

**Comment by glimchb** [comment]
check also https://github.com/googleapis/googleapis/blob/449686b58eaee7df382c2020f5069769deebde17/google/cloud/dataqna/v1alpha/question.proto#L43-L48

**Comment by jainvipin** [comment]
should we go with

**Comment by artek-koltun** [comment]
https://github.com/aip-dev/google.aip.dev/pull/1201

**Comment by glimchb** [comment]
sounds promising... waiting for [this](https://github.com/aip-dev/google.aip.dev/pull/1201) to be merged... 
```
  string name = 1 [(google.api.field_behavior) = IDENTIFIER];
```

**Comment by noahdietz** [comment]
https://github.com/aip-dev/google.aip.dev/pull/1201 is merged 😉 linter rules to follow if y'all use it...

**Comment by glimchb** [comment]
we do, renovate linter update #341

**Comment by glimchb** [comment]
new linter PR to enforce `IDENTIFIER` is merge https://github.com/googleapis/api-linter/pull/1241

**Comment by glimchb** [comment]
waiting on the new release https://github.com/googleapis/api-linter/releases

**Comment by noahdietz** [comment]
The rules are not available in: https://github.com/googleapis/api-linter/releases/tag/v1.57.0
