### ISSUE TITLE
code generator protoc-gen-grpc-gateway hasn't been updated to support optional fields in proto3

### ISSUE THREAD

**Issue by chujieyang** [opiproject/opi-api#332]
see https://github.com/grpc-ecosystem/grpc-gateway/issues/1278
see https://github.com/namely/docker-protoc/pull/361

An exception occurs when I use namely/protoc-all:1.51_2 with the parameter: --with-gateway to convert a proto file to a REST service:

```
... is a proto3 file that contains optional fields, but code generator protoc-gen-grpc-gateway hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--grpc-gateway_out:
make: *** [Makefile:9: all] Error 1

```
Would like to update the protoc version in the namely/protoc-all mirror to support this.

**Comment by glimchb** [comment]
trying to enable grpc gw for inventory #359
