### ISSUE TITLE
OPI Security API Spec and Protobuf

### ISSUE THREAD

**Issue by mestery** [opiproject/opi-api#58]
Tracking an initial cut at the OPI Security API. This will at first be IPsec tunnels.

**Comment by dandaly** [comment]
Hi,
  Really basic question on this one, why would we define a new protobuf for this as opposed to re-using an existing gRPC based protocol like OpenConfig and defining it in this way?
  
    By leveraging OpenConfig all of the security considerations that have been worked out (mutual TLS, etc.) come for free.  And if there are other configurations that we want to do, we can define all of these using either standard OpenConfig schemas or create our own OPI-specific schemas.

**Comment by mestery** [comment]
> Hi, Really basic question on this one, why would we define a new protobuf for this as opposed to re-using an existing gRPC based protocol like OpenConfig and defining it in this way?
> 
> ```
> By leveraging OpenConfig all of the security considerations that have been worked out (mutual TLS, etc.) come for free.  And if there are other configurations that we want to do, we can define all of these using either standard OpenConfig schemas or create our own OPI-specific schemas.
> ```

Because we have to start somewhere with actual code and protobufs. If you can point me at the OpenConfig IPsec protobufs (I can't find them), I will take a look.

**Comment by mestery** [comment]
Closed by https://github.com/opiproject/opi-api/pull/59.
