### ISSUE TITLE
storage: move from `ID` to `UUID` everywhere in proto

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-api#70]
also return UUID where `// Intentionally empty.` is

**Comment by mestery** [comment]
Look at https://github.com/opiproject/opi-api/pull/67 for how to do this.

**Comment by glimchb** [comment]
check out #143 as well before working on this

**Comment by glimchb** [comment]
since there is a disagreement about usage of UUID as an object handle, closing this issue. Discussion is happening on #143
