### ISSUE TITLE
Network: Expand use case(s) for networking

### ISSUE THREAD

**Issue by sandersms** [opiproject/opi-api#86]
1) Define the requirements for each use case
2) Address the usage of the OVS DB, Openflow, OpenConfig, P4, etc.
3) Map the use case with the various APIs that need to be considered to support the use of OVS, SONiC, VPP, SONiC in the networking functionality that can reside in the xPU
4) Include operations such as switching, routing, firewall in the use cases and API
5) Include the scope for ports, links, vnets, etc.

**Comment by jainvipin** [comment]
cloud API proposal in #128
