### ISSUE TITLE
Network: Expand LAN Service specifics in Network Readme

### ISSUE THREAD

**Issue by sandersms** [opiproject/opi-api#89]

**Comment by glimchb** [comment]
@sandersms see examples in inventory space
* https://github.com/opiproject/opi-prov-life/issues/144
* https://github.com/opiproject/opi-prov-life/blob/main/INVENTORY.md

**Comment by sandersms** [comment]
Updated Readme on Feb 16, 2024 checkin with additional LAN service specifics
